### 1. 더미데이터 생성
- create_dummy()

In [27]:
import random
import datetime
import time
import pandas as pd

def create_dummy():
    # Define the range of values for each vital sign
    heart_rate_range = (60, 100)
    oxygen_saturation_range = (95, 100)
    body_temperature_range = (36.0, 37.5)
    step_stride_range = (60, 80)

    # Define a list of 10 names for our construction workers
    names = ['최정인', '김민수', '손재우', '윤진식', '박경관', '금민경', '최한수', '이정민', '이창현', '김찬준']

    # Define the start and end times for the generated data
    start_time = datetime.datetime(2023, 2, 21, 0, 0, 0)  # February 21st, 2023, 12:00:00 AM
    end_time = datetime.datetime(2023, 2, 22, 0, 0, 0)  # February 22nd, 2023, 12:00:00 AM
    
    # start_time = datetime.datetime.now()
    # end_time = start_time + datetime.timedelta(seconds = 1)
    # Define the time intervals between measurements (in seconds)
    time_interval = 1

    # Define the standard deviation for the normal distribution of each vital sign
    heart_rate_stddev = 5
    oxygen_saturation_stddev = 1
    body_temperature_stddev = 0.1
    step_stride_stddev = 2

    # Define the range of values for GPS coordinates, gyrosensor readings, and accelerometer readings
    gps_latitude_range = [35.168008 , 35.169691]  # Busan, Republic of Korea
    gps_longitude_range = [129.139300, 129.141249]  # Busan, Republic of Korea
    gyrosensor_x_range = (-10, 10)
    gyrosensor_y_range = (-10, 10)
    gyrosensor_z_range = (-10, 10)
    accelerometer_x_range = (-2, 2)
    accelerometer_y_range = (-2, 2)
    accelerometer_z_range = (-2, 2)

    # Define the range of values for worker ID and age
    worker_id_range = (1000, 1010)
    age_range = (25, 55)

    # Define an empty list to hold the generated data
    construction_workers = []
    # Loop through each worker and generate their data for every second of the day
    for name in names:
        current_time = start_time
        heart_rate = random.randint(*heart_rate_range)
        oxygen_saturation = random.randint(*oxygen_saturation_range)
        body_temperature = round(random.uniform(*body_temperature_range), 1)
        step_stride = random.randint(*step_stride_range)
        gps_latitude = round(random.uniform(*gps_latitude_range), 6)
        gps_longitude = round(random.uniform(*gps_longitude_range), 6)
        gyrosensor_x = random.uniform(*gyrosensor_x_range)
        gyrosensor_y = random.uniform(*gyrosensor_y_range)
        gyrosensor_z = random.uniform(*gyrosensor_z_range)
        accelerometer_x = random.uniform(*accelerometer_x_range)
        accelerometer_y = random.uniform(*accelerometer_y_range)
        accelerometer_z = random.uniform(*accelerometer_z_range)
        worker_id = random.randint(*worker_id_range)
        age = random.randint(*age_range)
        password = ''.join(random.choices('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', k=8))
        for i in range(int((end_time - start_time).total_seconds())):
            heart_rate += random.normalvariate(0, heart_rate_stddev)
            heart_rate = max(min(round(heart_rate), heart_rate_range[1]), heart_rate_range[0])
            oxygen_saturation += random.normalvariate(0, oxygen_saturation_stddev)
            oxygen_saturation = max(min(round(oxygen_saturation), oxygen_saturation_range[1]), oxygen_saturation_range[0])
            body_temperature += random.normalvariate(0, body_temperature_stddev)
            body_temperature = max(min(round(body_temperature, 1), body_temperature_range[1]), body_temperature_range[0])
            step_stride += random.normalvariate(0, step_stride_stddev)
            step_stride = max(min(round(step_stride), step_stride_range[1]), step_stride_range[0])
            gps_latitude += random.uniform(-0.0001, 0.0001)
            gps_latitude = max(min(round(gps_latitude, 6), gps_latitude_range[1]), gps_latitude_range[0])
            gps_longitude += random.uniform(-0.0001, 0.0001)
            gps_longitude = max(min(round(gps_longitude, 6), gps_longitude_range[1]), gps_longitude_range[0])
            gyrosensor_x += random.uniform(-0.05, 0.05)
            gyrosensor_x = max(min(round(gyrosensor_x, 17), gyrosensor_x_range[1]), gyrosensor_x_range[0])
            gyrosensor_y += random.uniform(-0.05, 0.05)
            gyrosensor_y = max(min(round(gyrosensor_y, 17), gyrosensor_y_range[1]), gyrosensor_y_range[0])
            gyrosensor_z += random.uniform(-0.05, 0.05)
            gyrosensor_z = max(min(round(gyrosensor_z, 17), gyrosensor_z_range[1]), gyrosensor_z_range[0])
            accelerometer_x += random.uniform(-0.02, 0.02)
            accelerometer_x = max(min(round(accelerometer_x, 17), accelerometer_x_range[1]), accelerometer_x_range[0])
            accelerometer_y += random.uniform(-0.02, 0.02)
            accelerometer_y = max(min(round(accelerometer_y, 17), accelerometer_y_range[1]), accelerometer_y_range[0])
            accelerometer_z += random.uniform(-0.02, 0.02)
            accelerometer_z = max(min(round(accelerometer_z, 17), accelerometer_z_range[1]), accelerometer_z_range[0])
            row = {
                'Name': name,
                'Time': current_time,
                'Heart Rate': heart_rate,
                'Oxygen Saturation': oxygen_saturation,
                'Body Temperature': body_temperature,
                'Step Stride': step_stride,
                'GPS Latitude': gps_latitude,
                'GPS Longitude': gps_longitude,
                'Gyrosensor X': gyrosensor_x,
                'Gyrosensor Y': gyrosensor_y,
                'Gyrosensor Z': gyrosensor_z,
                'Accelerometer X': accelerometer_x,
                'Accelerometer Y': accelerometer_y,
                'Accelerometer Z': accelerometer_z,
                'Worker ID': worker_id,
                'Age': age,
                'Password': password
            }
            construction_workers.append(row)
            current_time += datetime.timedelta(seconds=time_interval)
       
    return construction_workers

In [28]:
dummy_data = pd.DataFrame(create_dummy())
dummy_data

,Name,Time,Heart Rate,Oxygen Saturation,Body Temperature,Step Stride,GPS Latitude,GPS Longitude,Gyrosensor X,Gyrosensor Y,Gyrosensor Z,Accelerometer X,Accelerometer Y,Accelerometer Z,Worker ID,Age,Password
0,최정인,2023-02-21 00:00:00,100,99,37.5,60,35.168113,129.139657,7.046792,-1.677604,5.269597,-1.724888,1.528355,-1.550819,1008,39,mWvJZNcJ
1,최정인,2023-02-21 00:00:01,100,100,37.4,60,35.168117,129.139628,7.031276,-1.705278,5.267999,-1.720009,1.522995,-1.564451,1008,39,mWvJZNcJ
2,최정인,2023-02-21 00:00:02,95,100,37.4,62,35.168182,129.139561,7.054641,-1.720923,5.235077,-1.715875,1.508896,-1.560738,1008,39,mWvJZNcJ
3,최정인,2023-02-21 00:00:03,100,99,37.4,62,35.168145,129.139485,7.028464,-1.687901,5.195639,-1.733250,1.499226,-1.561931,1008,39,mWvJZNcJ
4,최정인,2023-02-21 00:00:04,100,100,37.3,64,35.168155,129.139440,7.016946,-1.670956,5.165522,-1.716240,1.482852,-1.573932,1008,39,mWvJZNcJ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863995,김찬준,2023-02-21 23:59:55,70,100,36.2,69,35.169529,129.141061,4.662157,-0.249568,6.084355,-0.855213,-1.916638,-1.660281,1005,42,TTcMeHYM
863996,김찬준,2023-02-21 23:59:56,70,100,36.2,64,35.169554,129.140971,4.644014,-0.208756,6.075828,-0.858852,-1.929292,-1.679842,1005,42,TTcMeHYM
863997,김찬준,2023-02-21 23:59:57,71,100,36.2,65,35.169516,129.140999,4.603169,-0.202778,6.040599,-0.865183,-1.923670,-1.688400,1005,42,TTcMeHYM
863998,김찬준,2023-02-21 23:59:58,66,100,36.1,65,35.169455,129.141078,4.560104,-0.221284,6.005361,-0.855725,-1.906013,-1.685105,1005,42,TTcMeHYM
863999,김찬준,2023-02-21 23:59:59,69,100,36.2,67,35.169426,129.141002,4.552734,-0.173627,6.012935,-0.862902,-1.918688,-1.700299,1005,42,TTcMeHYM

In [9]:
activity = dummy_data[['Worker ID', 'Accelerometer X', 'Accelerometer Y', 'Accelerometer Z', 'Gyrosensor X', 'Gyrosensor Y', 'Gyrosensor Z' ]]
activity

,Worker ID,Accelerometer X,Accelerometer Y,Accelerometer Z,Gyrosensor X,Gyrosensor Y,Gyrosensor Z
0,1009,0.982229,-1.084454,-0.844277,-7.471126,-0.721001,9.517171
1,1009,0.964400,-1.066096,-0.849944,-7.486079,-0.770093,9.509484
2,1009,0.960515,-1.065072,-0.845527,-7.467957,-0.742922,9.548977
3,1009,0.956303,-1.077419,-0.833881,-7.424125,-0.787585,9.521380
4,1009,0.975234,-1.071613,-0.850843,-7.427987,-0.830221,9.482573
...,...,...,...,...,...,...,...
863995,1007,-0.518573,-0.323478,0.660878,5.198763,-6.886461,-2.884812
863996,1007,-0.503772,-0.332560,0.646816,5.181410,-6.888191,-2.905130
863997,1007,-0.487427,-0.345563,0.627214,5.230536,-6.936139,-2.894253
863998,1007,-0.495860,-0.349088,0.638068,5.266532,-6.897844,-2.891575
863999,1007,-0.479012,-0.363470,0.624459,5.274944,-6.907401,-2.904122

In [90]:
pd.to_timedelta(3*1000000000)

Timedelta('0 days 00:00:03')

### 기타 정보 더미데이터 생성
- deviceName : ph, w
- battery : 100 - a
- position
- role
- employDate
- workPlace
- onWork
- offWork
- attend

In [1]:
import datetime
from dateutil.relativedelta import relativedelta
from faker import Faker

def create_etc_dummy():

    # Define a list of 10 names for our construction workers
    device = ['ph', 'w']
    job_position = ['부장', '과장', '대리', '주임', '사원']
    job_role = ['철골', '조적', '방수', '미장', '목공', '콘크리트']
    job_workPlace = ['A', 'B', 'C']
    userId = list(activity['Worker ID'].unique())
    work_attend = [0,1]
    
    # Faker 
    fake = Faker()
    
    # Define the range of values for each vital sign
    battery_range = (0, 100)

    # Define the start and end times for the generated data    
    start_time = datetime.datetime(2023, 2, 21, 0, 0, 0)  # February 21st, 2023, 12:00:00 AM
    end_time = datetime.datetime(2023, 2, 22, 0, 0, 0)  # February 22nd, 2023, 12:00:00 AM
    
    work_start = datetime.datetime(2023, 2, 21, 5 , 0, 0)  # February 21st, 2023, 05:30:00 AM
    timdDiff_onWork = datetime.timedelta(minutes=30)
    
    work_end = datetime.datetime(2023, 2, 21, 15 , 0, 0)
    timdDiff_offWork = datetime.timedelta(hours = 3)
    
    # Define the time intervals between measurements (in seconds)
    time_interval = 1
    device_interval = 20
    battery_stddev = 2

    # Define an empty list to hold the generated data
    workers_info = []
    
    # Loop through each worker and generate their data for every second of working Day
    for id in userId:
        current_time = start_time
        deviceName = device[random.randint(0,1)]
        position = job_position[random.randint(0,4)]
        role = job_role[random.randint(0,5)]
        workPlace = job_workPlace[random.randint(0,2)]
        battery = 100 
        hired_date = fake.date_between(start_date='-20y', end_date='today')
        
        onWork = fake.date_time_between(start_date=work_start, end_date= work_start + timdDiff_onWork)
        if current_time > onWork:
            onWork = "-"
        else :
            onWork = onWork
        
        offWork = fake.date_time_between(start_date=work_end, end_date= work_end + timdDiff_offWork)
        if current_time <= offWork:
            offWork = offWork
        else : 
            offWork = "-"

        if onWork != "-" and offWork !="-":
            attend = 1
        else:
            attend = 0
        for i in range(int((end_time - start_time).total_seconds())):   

            battery -= random.normalvariate(0, battery_stddev)
            battery = max(min(round(battery), battery_range[1]), battery_range[0])

            row = {
                'Time': current_time,
                'userId' : id,
                'battery' : battery,
                'deviceName': deviceName, 
                'position': position,
                'role': role,
                'employDate': hired_date,
                'workPlace': workPlace,
                'onWork': onWork,
                'offWork': offWork,
                'attend': attend
            }
            workers_info.append(row)
            current_time += datetime.timedelta(seconds=time_interval)
    return workers_info

In [2]:
etc = pd.DataFrame(create_etc_dummy())
etc

NameError: name 'pd' is not defined

In [218]:
from faker import Faker
fake = Faker()
start_time = datetime.datetime(2023, 2, 21, 0, 0, 0)  # February 21st, 2023, 12:00:00 AM
end_time = datetime.datetime(2023, 2, 22, 0, 0, 0)  # February 22nd, 2023, 12:00:00 AM

work_start = datetime.datetime(2023, 2, 21, 5 , 0, 0)  # February 21st, 2023, 05:30:00 AM
timdDiff_onWork = datetime.timedelta(minutes=30)

work_end = datetime.datetime(2023, 2, 21, 15 , 0, 0)
timdDiff_offWork = datetime.timedelta(hours = 3)

onWork = fake.date_time_between(start_date=work_start, end_date= work_start + timdDiff_onWork)

time_interval = 1

current_time  = start_time
current_time += datetime.timedelta(seconds=time_interval)

### DB 연결 및 데이터 insert

In [86]:
def main():
    # 입력할 db 선택
    conn = selectDB()
    try:
        with conn.cursor() as cursor:
            sql, list = selectTable()
            cursor.executemany(sql, list)
        conn.commit()

    finally:
        conn.close()

# 입력할 DB 선택
def selectDB():
    print("Select the Database")
    print("		1. 팀 AWS - keepme")
    print("		2. 정인 AWS - keepme")
    print("		3. 정인 로컬 - keepme")
    selNum = int(input("Enter the number: "))

    if selNum == 1:
        conn = pymysql.connect(host='database-1.cani4y1t2hfg.ap-northeast-2.rds.amazonaws.com', database='keepme', user='slows14tem', password='!wjdgy0117')
    elif selNum == 2:
        conn = pymysql.connect(host='keepme.c2ve8hvd51l9.ap-northeast-2.rds.amazonaws.com', 
            database='keepme', user='admin', password='tiger123')
    elif selNum == 3:
        conn = pymysql.connect(host='localhost', 
            database='keepme', user='keepme', password='tiger')

    return conn

# 입력할 테이블 선택
def selectTable():
    print("Select the Table")
    print("		1. activity")
    print("		2. device")
    print("		3. gps")
    print("		4. status")
    print("		5. user")
    print("		6. vitalsign")
    print("		7. work_schedules")
    selNum = int(input("Enter the number: "))

    if selNum == 1:
        sql = 'INSERT INTO activity (userId, accX, accY, accZ, gyroX, gyroY, gyroZ) VALUES (%s, %s, %s, %s, %s, %s, %s)'
        list = extract_activity()
    elif selNum == 2:
        sql = 'INSERT INTO device (userId, deviceName, battery) VALUES (%s, %s, %s)'
        list = extract_device()
    elif selNum == 3:
        sql = 'INSERT INTO gps (userId, lat, lon, recordTime) VALUES (%s, %s, %s, %s)'
        list = extract_gps()
    elif selNum == 4:
        sql = 'INSERT INTO status (userId, status, action) VALUES (%s, %s, %s)'
        list = extract_status()
    elif selNum == 5:
        sql = 'INSERT INTO user (id, pw, name, age, contact, position, role, employDate, workplace) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'
        list = extract_user()
    elif selNum == 6:
        sql = 'INSERT INTO vitalsign (userId, insertTime, heartRate, temp, o2, steps) VALUES (%s, %s, %s, %s, %s, %s)'
        list = extract_vitalsign()
    elif selNum == 7:
        sql = 'INSERT INTO work_schedules (userId, name, attend, onWork, offWork) VALUES (%s, %s, %s, %s, %s)'
        list = extract_work_schedules()

    return sql, list

# activity 테이블에 입력할 데이터 생성
def extract_activity():
    # dummy_data 에서 activity 테이블 컬럼만 추출
    activity = dummy_data[['Worker ID', 'Accelerometer X', 'Accelerometer Y', 'Accelerometer Z', 'Gyrosensor X', 'Gyrosensor Y', 'Gyrosensor Z' ]]

    # 컬럼 리스트 생성
    id_lst = activity['Worker ID'].to_list()
    accX_lst = activity['Accelerometer X'].to_list()
    accY_lst = activity['Accelerometer Y'].to_list()
    accZ_lst = activity['Accelerometer Z'].to_list()
    gyroX_lst = activity['Gyrosensor X'].to_list()
    gyroY_lst = activity['Gyrosensor Y'].to_list()
    gyroZ_lst = activity['Gyrosensor Z'].to_list()
    

    # 입력할 데이터 리스트 생성
    list_activity = []
    for i in range(len(act_lst)):
        data = id_lst[i], accX_lst[i], accY_lst[i], accZ_lst[i], gyroX_lst[i], gyroY_lst[i], gyroZ_lst[i]
        list_activity.append(data)

    return list_activity


# ship 테이블에 입력할 데이터 생성
def createShip():
    # 선박정보 불러오기
    ship = pd.read_csv('./ModelingDataset/portmis.csv', encoding = 'cp949')
    # 중복 제거
    ship = ship.drop_duplicates(subset='mmsi')
    # 컬럼 리스트 생성
    shipCode = ship.loc[:,'호출부호'].to_list()
    shipId = ship.loc[:,'mmsi'].to_list()
    shipName = ship.loc[:,'선명'].to_list()
    shipUse = ship.loc[:,'선박용도'].to_list()

    # 입력할 데이터 생성
    list_shipData = []
    for i in range(len(shipCode)) :
        data = shipId[i],shipCode[i], shipName[i], shipUse[i]
        list_shipData.append(data)

    return list_shipData


# shiplog 테이블에 입력할 데이터 생성
##230203 수기입력한 10개 선박 더미데이터
def createShiplog2():
	# csv 불러오기
	shiplog = pd.read_csv('./ModelingDataset/shipDummy.csv', encoding = 'cp949')
	# 컬럼 리스트 생성
	timeGroup = shiplog.loc[:, 'timeGroup'].to_list()
	ship_shipId = shiplog.loc[:,'shipId'].to_list()
	insertTime = shiplog.loc[:,'insertTime'].to_list()
	shipLat = shiplog.loc[:,'shipLat'].to_list()
	shipLon = shiplog.loc[:,'shipLon'].to_list()
	speed = shiplog.loc[:,'speed'].to_list()
	arrivalTime = shiplog.loc[:,'arrivalTime'].to_list()
	takeTime = shiplog.loc[:,'takeTime'].to_list()
	accuracy = shiplog.loc[:,'accuracy'].to_list()
	status = shiplog.loc[:,'status'].to_list()
	totalTakeTime = shiplog.loc[:,'totalTakeTime'].to_list()

	# 입력할 데이터 생성
	list_shiplogData = []
	for i in range(len(ship_shipId)) :
		data = timeGroup[i], ship_shipId[i], insertTime[i], shipLat[i], shipLon[i],
		speed[i], arrivalTime[i], takeTime[i], accuracy[i], status[i], totalTakeTime[i]
		list_shiplogData.append(data)

	return list_shiplogData


# weather 테이블에 입력할 데이터 생성
def createWeather():
    weather = pd.read_csv('./ModelingDataset/weather.csv', encoding = 'cp949', index_col = 0)
    weather.reset_index(drop = True)

    # 컬럼 리스트 생성
    num = []
    obsId = weather.iloc[:,0].to_list()
    time = weather.iloc[:,1].to_list()
    temp = weather.iloc[:,7].to_list()
    pressure = weather.iloc[:,8].to_list()
    windDirec= weather.iloc[:,6].to_list()
    windSpeed = weather.iloc[:,5].to_list()
    obsLat=weather.iloc[:,2].to_list()
    obsLon =weather.iloc[:,3].to_list()
    tideLevel = weather.iloc[:,4].to_list()

  # 입력할 데이터 생성
    list_weatherData = []
    for i in range(len(weather)) :
        a = i+1, obsId[i], time[i] ,temp[i],pressure[i],windDirec[i],windSpeed[i], round(obsLat[i],6),round(obsLon[i],6),tideLevel[i]
        list_weatherData.append(a)
    return list_weatherData

main()

IndentationError: unexpected indent (3344644946.py, line 39)